name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "3c4add8a-a13e-4589-97a3-f10d5d5d2294"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
